# -*- coding: utf-8 -*-
"""Virat_Kohli.ipynb

Automatically generated by Colaboratory.

Original file is located at
    https://colab.research.google.com/drive/1nA_ddqT2h5z1ubKG5k1qJOWQTFVuV-M0

## Virat Kohli Performance Analysis (Case Study)
Virat Kohli is one of the most famous cricketers in the world. Here you are given a dataset of all the ODI matches played by Virat Kohli from 18 August 2008 to 22 January 2017. You are required to analyze the performance of Virat Kohli in ODI matches.
"""

import pandas as pd
import numpy as np
import plotly.express as px
import plotly.graph_objects as go
import matplotlib.pyplot as plt
from matplotlib.pyplot import figure

data = pd.read_csv("Virat_Kohli.csv")
print(data.head())

# Checking for null values
data.isnull().sum()

"""Total runs scored by Virat Kohli"""

data["Runs"].sum()

"""Average"""

# In ODI 35-37 considered as good average. So, he has good avg in ODI
data["Runs"].mean()

fig = plt.figure(figsize=(20,8))
fig = px.bar(x=data.index,y=data["Runs"],title = "Runs Scored by Virat Kohli Between 18-Aug-08 - 22-Jan-17")
fig.show()

data["Pos"] = data["Pos"].map({3.0: "Batting At 3", 4.0: "Batting At 4", 2.0: "Batting At 2", 
                               1.0: "Batting At 1", 7.0:"Batting At 7", 5.0:"Batting At 5", 
                               6.0: "batting At 6"})

# Runs scored in various batting order, and he scored 72.4% of runs at batting at 3rd position
fig = px.pie(data,values ="Runs",names="Pos",title="Runs scored on each batting position")
fig.show()

data["Inns"].unique()

# he scored more runs while chasing
fig = px.pie(data,values ="Runs",names="Inns",title="Runs per Innings")
fig.show()

data["Dismissal"].unique()

data.head()

# Virat Kohli gets most `out by getting caught 
fig = plt.figure(figsize=(15,6))
plt.bar(data["Dismissal"].values,data["Dismissal"].index)
plt.title("Dismissals of Virat Kohli")
plt.show()

data.head()

# He scored most of the runs against Sri Lanka
fig = px.pie(data,values ="Runs",names="Opposition",title="Runs against countries")
fig.show()

# He has good strike rate at First Innings
plt.bar(data["Inns"],data["SR"])
plt.title("Runs scored in an Innings")
plt.show()

# there is linear relationship, as he scores more runs, the more fours he scores
figure = px.scatter(data_frame = data, x="Runs",
                    y="4s", size="SR", trendline="ols",title="Relationship Between Runs Scored and Fours")
figure.show()

# there is not linear relationship, as he scores more fours than sixes
figure = px.scatter(data_frame = data, x="Runs",
                    y="6s", size="SR", trendline="ols",title="Relationship Between Runs Scored and Fours")
figure.show()